// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDMaaap4Z2gNk0bBR33I5tArVUPeAlrcs',
    appId: '1:931872682599:web:6908815a8aa09338eb5ac2',
    messagingSenderId: '931872682599',
    projectId: 'finance-3d01b',
    authDomain: 'finance-3d01b.firebaseapp.com',
    storageBucket: 'finance-3d01b.appspot.com',
    measurementId: 'G-YC94530883',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiqXlMYl30TdV6X3U5_ZbTgUKa9lYZOvU',
    appId: '1:931872682599:android:40e73d6ecbd48972eb5ac2',
    messagingSenderId: '931872682599',
    projectId: 'finance-3d01b',
    storageBucket: 'finance-3d01b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqrmhaDEW9sXiuEAVXwQSEZyaGGxhFLhc',
    appId: '1:931872682599:ios:80735382d4dce399eb5ac2',
    messagingSenderId: '931872682599',
    projectId: 'finance-3d01b',
    storageBucket: 'finance-3d01b.appspot.com',
    iosClientId: '931872682599-st5061ma3aqrv8h9kn4c8liqk866umgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqrmhaDEW9sXiuEAVXwQSEZyaGGxhFLhc',
    appId: '1:931872682599:ios:80735382d4dce399eb5ac2',
    messagingSenderId: '931872682599',
    projectId: 'finance-3d01b',
    storageBucket: 'finance-3d01b.appspot.com',
    iosClientId: '931872682599-st5061ma3aqrv8h9kn4c8liqk866umgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.personalFinance',
  );
}
